#!/bin/sh

# Temporarily add Git Bash to PATH if it's not already in the PATH
if ! command -v bash &> /dev/null
then
    export PATH="$PATH:/c/Program Files/Git/usr/bin"
fi

npm run pre-commit
echo 'add linting to pre-commit when jan fixes his bot imports'
